v0.0.3
- Update Scala and Spark default version to 2.10.6 and 1.5.1
- `bin/run`: delete `$DEFAULT_SPARK_SUBMIT_OPTIONS` (`spark.driver.userClassPathFirst` may
  cause `java.lang.NoClassDefFoundError: org/apache/hadoop/util/VersionInfo` exception)